config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    root 'static_pages#index'
    get 'about', to: 'static_pages#about'
    get 'resume', to: 'static_pages#resume'
    get 'social_media', to: 'static_pages#social_media'
    resources :projects, only: [:new, :create, :index]
    resources :users, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/college.rb
class College < ApplicationRecord
    belongs_to :resume
end

app/models/company.rb
class Company < ApplicationRecord
    belongs_to :resume
end

app/models/honor.rb
class Honor < ApplicationRecord
    belongs_to :resume
end

app/models/project.rb
class Project < ApplicationRecord
  validates :title, presence: true
  validates :description, presence: true

  belongs_to :user
end

app/models/resume.rb
class Resume < ApplicationRecord
  has_many :skills
  has_many :colleges
  has_many :companies
  has_many :honors

  belongs_to :user
end

app/models/skill.rb
class Skill < ApplicationRecord
  belongs_to :resume
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :projects
  has_many :resumes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create]

  def new
    @project = Project.new
  end

  def index
    @projects = Project.all
  end

  def create
    current_user.projects.create(project_params)
    redirect_to projects_path
  end

  private

  def project_params
    params.require(:project).permit(:title, :description)
  end

end

app/controllers/resume_controller.rb
class ResumeController < ApplicationController
  def new
  end

  def create
  end

  def index
  end

  private

  def resume_params
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end
  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @projects = Project.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/resume_helper.rb
module ResumeHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Chris - Marasco Portfolio</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <div id="flex-content-container">
      <nav class="navbar navbar-toggleable-md navbar-inverse bg-inverse">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <%= link_to 'Chris Marasco', root_path, class: 'navbar-brand' %>

        <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
          <ul class="navbar-nav mr-auto mt-2 mt-md-0">
          <li class="nav-item">
            <%= link_to 'About', about_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Projects', projects_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Resume', resume_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Social Media', social_media_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Portfolio', '#', class: 'nav-link' %>
          </li>
          </ul>
          <ul class="navbar-nav">
            <% if user_signed_in? %>
                <li class="nav-item">
                  <%= link_to 'Dashboard', user_path(current_user), class: 'nav-link' %>
              </li>
              <li class="nav-item">
                <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'nav-link' %>
              </li>
            <% else %>
              <li class="nav-item">
                <%= link_to 'Sign in', new_user_session_path, class: 'nav-link' %>
              </li>
              <li class="nav-item">
                <%= link_to 'Sign up', new_user_registration_path, class: 'nav-link' %>
              </li>
            <% end %>
          </ul>

        </div>
    </nav>

      <% if notice.present? %>
        <p class="alert alert-info"><%= notice %></p>
      <% end %>
      <% if alert.present? %>
        <p class="alert alert-danger"><%= alert %></p>
      <% end %>
    <%= yield %>
        </div>

    <div id="footer">
      <div class="container">
      </div>
    </div>
  </body>
</html>

app/views/projects/index.html.erb
<div class="booyah-box col-10 offset-1">
  <h1 class="text-center">Projects</h1>
  <hr />
  <div class="col-10 offset-1 booyah-box">
      <% @projects.each do |project| %>
        <% if project.present? %>
            <b>Project Title:  </b><%= project.title %>
            <br />
            <b>Description:  </b><%= project.description %>
          <% end %>
        <br />
        <br />
      <% end %>
            </div>
      <hr>
      <div class="col-12 offset-1">
        <br />
          <%= link_to 'Create Project', new_project_path, class: 'btn btn-success' %>
      </div>
  <br />
  <br />
</div>

app/views/projects/new.html.erb
<br />
<div class="booyah-box col-10 offset-1">
  <h1>Add a new Project here</h1>
  <%= simple_form_for @project do |f| %>
    <%= f.input :title %>
    <%= f.input :description %>
    <br />
    <%= f.submit "Create",class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/static_pages/about.html.erb
<div class="booyah-box col-10 offset-1 text-center">
  <h1>About Me</h1>
  <hr />
</div>

app/views/static_pages/index.html.erb
<div class="hero">
  <br />
  <div class="frosty col-10 offset-1 text-center">
    <br />
    <h1>Chris Marasco</h1>
    <br />
    <h2>Software Developer and Systems Administrator</h2>
    <br />
    <br />
  </div>
</div>

app/views/static_pages/resume.html.erb
<div class="booyah-box col-10 offset-1 text-center">
  <h1>Resume</h1>
  <hr />
</div>

app/views/static_pages/social_media.html.erb
<div class="booyah-box col-10 offset-1 text-center">
  <h1>Social Media</h1>
  <hr />
</div>

app/views/users/show.html.erb
<div class="booyah-box col-10 offset-1">
  <h1 class="text-center">Dashboard</h1>
  <hr>
  <br />
  <br />
  <h2>Resume</h2>
  <br />
  <h2>Projects</h2>
  <div class="booyah-box">
    <% @projects.each do |project| %>
      <b>Project Title:  </b><%= project.title %>
      <br />
      <b>Description:  </b><%= project.description %>
    </div>
    <% end %>
  <br />
</div>